version: '3.0'

services:
  grafana:
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-11.0.0}
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
      - GF_USERS_DEFAULT_THEME=system
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
